/*Exercise4_FUNCTION 함수
Update : 2018-02-18, Kang Han.

아래의 SQL은 『SQL 전문가 가이드』에 따른 연습입니다.*/

/*p.230 _ DUAL table*/
DESC DUAL;

SELECT *
FROM DUAL;

/*p.229 _ 단일행 문자형 함수 예제*/
SELECT LOWER('SQL Expert')
FROM DUAL;

SELECT UPPER('SQL Expert')
FROM DUAL;

SELECT ASCII('A')
FROM DUAL;

SELECT CHR(65)
FROM DUAL;

SELECT CONCAT('RDBMS',' SQL')
FROM DUAL;

SELECT 'RDBMS'||' SQL'
FROM DUAL;

SELECT SUBSTR('SQL Expert', 5, 3)
FROM DUAL;

SELECT LENGTH('SQL Expert')
FROM DUAL;

SELECT LTRIM('xxxYYZZxYZ','x')
FROM DUAL;

SELECT RTRIM('XXYYzzYYzz','z')
FROM DUAL;

SELECT TRIM('x' FROM 'xxYYZZxYZxx')
FROM DUAL;

SELECT RTRIM('XXYYZZXYZ       ')
FROM DUAL;


/*p.230 예제*/
SELECT LENGTH('SQL Expert')
FROM DUAL;

/*p.231 예제 _ CONCAT 문자형 함수 이용*/
SELECT CONCAT(PLAYER_NAME, ' 축구선수') 선수명
FROM PLAYER;

SELECT PLAYER_NAME || ' 축구선수' AS 선수명
FROM PLAYER;

SELECT PLAYER_NAME || ' 축구선수' 선수명
FROM PLAYER;

SELECT STADIUM_ID, DDD||TEL AS TEL, LENGTH(DDD||TEL) AS T_LEN
FROM STADIUM;
