/*Exercise2_TCL(Transaction Control Language)
Update : 2018-02-07, Kang Han.

아래의 SQL은 『SQL 전문가 가이드』에 따른 연습입니다.*/

/*p.194
2. COMMIT*/

DESC PLAYER;

INSERT INTO PLAYER
(PLAYER_ID, TEAM_ID, PLAYER_NAME, POSITION, HEIGHT, WEIGHT, BACK_NO)
VALUES ('1997035', 'K02', '이운재', 'GK', 182, 82, 1);

COMMIT;

SELECT *
FROM PLAYER;

UPDATE PLAYER
SET HEIGHT = 100;

COMMIT;

SELECT PLAYER_ID, PLAYER_NAME, HEIGHT
FROM PLAYER;

DELETE FROM PLAYER;

COMMIT;

SELECT *
FROM PLAYER;