/*Exercise6_ORDER BY 절
Update : 2018-02-26, Kang Han.

아래의 SQL은 『SQL 전문가 가이드』에 따른 연습입니다.*/

SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
FROM PLAYER
ORDER BY PLAYER_NAME DESC;

SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
FROM PLAYER
ORDER BY 포지션 DESC;

SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE HEIGHT IS NOT NULL
ORDER BY HEIGHT DESC, BACK_NO;

SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
FROM PLAYER
WHERE BACK_NO IS NOT NULL
ORDER BY 3 DESC, 2, 1;

SELECT DNAME, LOC, DEPTNO
FROM DEPT
ORDER BY DNAME, LOC, DEPTNO DESC;

SELECT DNAME DEPT, LOC AREA, DEPTNO
FROM DEPT
ORDER BY DNAME, AREA, DEPTNO DESC;

SELECT DNAME, LOC AREA, DEPTNO
FROM DEPT
ORDER BY 1, AREA, 3 DESC;


/*p.274~ SELECT 문장 실행 순서*/
SELECT EMPNO, ENAME
FROM EMP
ORDER BY MGR;

SELECT EMPNO, ENAME, MGR
FROM EMP
ORDER BY MGR;

SELECT EMPNO FROM
    (SELECT EMPNO, ENAME FROM EMP ORDER BY MGR);

SELECT MGR FROM
    (SELECT EMPNO, ENAME FROM EMP ORDER BY MGR);
/*위의 SQL 문장은 오류를 발생시킨다.*/

SELECT JOB, SAL
FROM EMP
GROUP BY JOB
HAVING COUNT(*) > 0
ORDER BY SAL;
/*위의 SQL 문장은 오류를 발생시킨다.*/

SELECT JOB
FROM EMP
GROUP BY JOB
HAVING COUNT(*) > 0
ORDER BY SAL;
/*위의 SQL 문장은 오류를 발생시킨다.*/

SELECT JOB
FROM EMP
GROUP BY JOB
HAVING COUNT(*) > 0
ORDER BY MAX(EMPNO), MAX(MGR), SUM(SAL), COUNT(DEPTNO), MAX(HIREDATE);


/*p.277~ Top N 쿼리*/
SELECT ENAME, SAL
FROM EMP
WHERE ROWNUM < 4
ORDER BY SAL DESC;
/*위 SQL 문장은 잘못 사용된 예다.*/

SELECT ENAME, SAL
FROM (SELECT ENAME, SAL
      FROM EMP
      ORDER BY SAL DESC)
WHERE ROWNUM < 4;