/*Exercise5_GROUP BY, HAVING 절
Update : 2018-02-25, Kang Han.

아래의 SQL은 『SQL 전문가 가이드』에 따른 연습입니다.*/

/*p.256~ */
SELECT COUNT(*) "전체 행수", COUNT(HEIGHT) "키 건수",
       MAX(HEIGHT) 최대키, MIN(HEIGHT) 최소키, ROUND(AVG(HEIGHT),2) 평균키
FROM PLAYER;

SELECT POSITION 포지션, AVG(HEIGHT) 평균키
FROM PLAYER;
/*GROUP BY 절에서 그룹 단위를 표시해 주어야 SELECT 절에서 그룹 단위의 칼럼과 집계함수를
사용할 수 있다. 그렇지 않으면 위 예제와 같이 에러를 발생하게 된다.*/

SELECT POSITION 포지션, AVG(HEIGHT) 평균키
FROM PLAYER
GROUP BY POSITION 포지션;
/*실행 결과를 살펴보면 GROUP BY 절에 “포지션”이라고 표시된 부분에 에러가 발생했다는 것을
알 수 있다. 칼럼에 대한 ALIAS는 SELECT 절에서 정의하고 ORDER BY 절에서는 재활용할 수 있지만,
GROUP BY 절에서는 ALIAS 명을 사용할 수 없다는 것을 보여 주는 사례다.*/

SELECT POSITION 포지션, COUNT(*) 인원수, COUNT(HEIGHT) 키대상,
       MAX(HEIGHT) 최대키, MIN(HEIGHT) 최소키, ROUND(AVG(HEIGHT),2) 평균키
FROM PLAYER
GROUP BY POSITION;

SELECT POSITION 포지션, ROUND(AVG(HEIGHT),2) 평균키
FROM PLAYER
WHERE AVG(HEIGHT) >= 180
GROUP BY POSITION;
/*실행 결과에서 WHERE 절의 집계함수 “AVG(HEIGHT)” 부분에서 “집계 함수는 허가되지 않는다”는
에러 메시지가 출력됐다. 즉, WHERE 절에는 AVG()라는 집계함수를 사용할 수 없다.*/

SELECT POSITION 포지션, ROUND(AVG(HEIGHT),2) 평균키
FROM PLAYER
GROUP BY POSITION
HAVING AVG(HEIGHT) >= 180;

/*GROUP BY 절과 HAVING 절의 순서를 바꿔서 수행한다.*/
SELECT POSITION 포지션, ROUND(AVG(HEIGHT),2) 평균키
FROM PLAYER
HAVING AVG(HEIGHT) > 180
GROUP BY POSITION;

SELECT TEAM_ID 팀ID, COUNT(*) 인원수
FROM PLAYER
WHERE TEAM_ID IN ('K09', 'K02')
GROUP BY TEAM_ID;

SELECT TEAM_ID 팀ID, COUNT(*) 인원수
FROM PLAYER
GROUP BY TEAM_ID
HAVING TEAM_ID IN ('K09', 'K02');

SELECT POSITION 포지션, ROUND(AVG(HEIGHT),2) 평균키
FROM PLAYER
GROUP BY POSITION
HAVING MAX(HEIGHT) >= 190;


/*p.262~ CASE 표현을 활용한 월별 데이터 집계*/
SELECT ENAME, DEPTNO, EXTRACT(MONTH FROM HIREDATE) 입사월, SAL
FROM EMP;

SELECT ENAME, DEPTNO,
    CASE MONTH WHEN  1 THEN SAL END M01,  CASE MONTH WHEN  2 THEN SAL END M02,
    CASE MONTH WHEN  3 THEN SAL END M03,  CASE MONTH WHEN  4 THEN SAL END M04,
    CASE MONTH WHEN  5 THEN SAL END M05,  CASE MONTH WHEN  6 THEN SAL END M06,
    CASE MONTH WHEN  7 THEN SAL END M07,  CASE MONTH WHEN  8 THEN SAL END M08,
    CASE MONTH WHEN  9 THEN SAL END M09,  CASE MONTH WHEN 10 THEN SAL END M10,
    CASE MONTH WHEN 11 THEN SAL END M11,  CASE MONTH WHEN 12 THEN SAL END M12
FROM (SELECT ENAME, DEPTNO, EXTRACT(MONTH FROM HIREDATE) MONTH, SAL
      FROM EMP);

SELECT DEPTNO,
       AVG(CASE MONTH WHEN  1 THEN SAL END) M01,
       AVG(CASE MONTH WHEN  2 THEN SAL END) M02,
       AVG(CASE MONTH WHEN  3 THEN SAL END) M03,
       AVG(CASE MONTH WHEN  4 THEN SAL END) M04,
       AVG(CASE MONTH WHEN  5 THEN SAL END) M05,
       AVG(CASE MONTH WHEN  6 THEN SAL END) M06,
       AVG(CASE MONTH WHEN  7 THEN SAL END) M07,
       AVG(CASE MONTH WHEN  8 THEN SAL END) M08,
       AVG(CASE MONTH WHEN  9 THEN SAL END) M09,
       AVG(CASE MONTH WHEN 10 THEN SAL END) M10,
       AVG(CASE MONTH WHEN 11 THEN SAL END) M11,
       AVG(CASE MONTH WHEN 12 THEN SAL END) M12
FROM (SELECT ENAME, DEPTNO, EXTRACT(MONTH FROM HIREDATE) MONTH, SAL
      FROM EMP)
GROUP BY DEPTNO;

SELECT DEPTNO,
    AVG(DECODE(MONTH, 1,SAL)) M01, AVG(DECODE(MONTH, 2,SAL)) M02,
    AVG(DECODE(MONTH, 3,SAL)) M03, AVG(DECODE(MONTH, 4,SAL)) M04,
    AVG(DECODE(MONTH, 5,SAL)) M05, AVG(DECODE(MONTH, 6,SAL)) M06,
    AVG(DECODE(MONTH, 7,SAL)) M07, AVG(DECODE(MONTH, 8,SAL)) M08,
    AVG(DECODE(MONTH, 9,SAL)) M09, AVG(DECODE(MONTH,10,SAL)) M10,
    AVG(DECODE(MONTH,11,SAL)) M11, AVG(DECODE(MONTH,12,SAL)) M12
FROM (SELECT ENAME, DEPTNO, EXTRACT(MONTH FROM HIREDATE) MONTH, SAL
      FROM EMP)
GROUP BY DEPTNO;


/*p.265~ 집계함수와 NULL 처리*/
SELECT TEAM_ID,
      NVL(SUM(CASE POSITION WHEN 'FW' THEN 1 ELSE 0 END),0) FW,
      NVL(SUM(CASE POSITION WHEN 'MF' THEN 1 ELSE 0 END),0) MF,
      NVL(SUM(CASE POSITION WHEN 'DF' THEN 1 ELSE 0 END),0) DF,
      NVL(SUM(CASE POSITION WHEN 'GK' THEN 1 ELSE 0 END),0) GK,
      COUNT(*) SUM
FROM PLAYER
GROUP BY TEAM_ID;

SELECT TEAM_ID,
      NVL(SUM(CASE POSITION WHEN 'FW' THEN 1 END),0) FW,
      NVL(SUM(CASE POSITION WHEN 'MF' THEN 1 END),0) MF,
      NVL(SUM(CASE POSITION WHEN 'DF' THEN 1 END),0) DF,
      NVL(SUM(CASE POSITION WHEN 'GK' THEN 1 END),0) GK,
      COUNT(*) SUM
FROM PLAYER
GROUP BY TEAM_ID;

SELECT TEAM_ID,
      NVL(SUM(CASE WHEN POSITION = 'FW' THEN 1 END), 0) FW,
      NVL(SUM(CASE WHEN POSITION = 'MF' THEN 1 END), 0) MF,
      NVL(SUM(CASE WHEN POSITION = 'DF' THEN 1 END), 0) DF,
      NVL(SUM(CASE WHEN POSITION = 'GK' THEN 1 END), 0) GK,
      COUNT(*) SUM
FROM PLAYER
GROUP BY TEAM_ID;

SELECT ROUND(AVG(CASE WHEN POSITION = 'MF' THEN HEIGHT END),2) 미드필더,
       ROUND(AVG(CASE WHEN POSITION = 'FW' THEN HEIGHT END),2) 포워드,
       ROUND(AVG(CASE WHEN POSITION = 'DF' THEN HEIGHT END),2) 디펜더,
       ROUND(AVG(CASE WHEN POSITION = 'GK' THEN HEIGHT END),2) 골키퍼,
       ROUND(AVG(HEIGHT),2) 전체평균키
FROM PLAYER;