/*Exercise.*/
/*Update : 2018-02-03, Kang Han.*/

/*『SQL 전문가 가이드』에 따른 연습이다.*/

/*p.166 테이블 구조 확인*/
DESCRIBE CAEMP;

DESC CAEMP;

/*p.168 SELECT 문장을 통한 테이블 생성 사례*/
CREATE TABLE CAEMP_TEMP
AS SELECT * FROM CAEMP;

DESC CAEMP_TEMP;

/*p.169 ALTER TABLE*/
/*ADD COLUMN*/
ALTER TABLE CAEMP
ADD (MARRIAGE VARCHAR2(20));

DESC CAEMP;

/*DROP COLUMN*/
ALTER TABLE CAEMP
DROP COLUMN MARRIAGE;

DESC CAEMP;

/*p.176 ADD CONSTRAINT*/
ALTER TABLE CAEMP
ADD CONSTRAINT CAEMP_PK PRIMARY KEY (NAME);

DESC CAEMP;

/*p.186 DISTINCT 옵션*/
SELECT ALL JOB
FROM CAEMP;

SELECT JOB
FROM CAEMP;

SELECT DISTINCT JOB
FROM CAEMP;

SELECT CONCAT(NAME,' 씨') 직원명
FROM CAEMP;

SELECT NAME||' 씨' AS 선수명
FROM CAEMP;

/*제3절 DML(DATA MANIPULATION LANGUAGE)에 해당되는 내용 연습.*/
DESC CAEMP;

SELECT *
FROM CAEMP;

INSERT INTO CAEMP
    (EMPNO, NAME, JOB, MGR, PHONE, EMAIL, ADDRESS, HIREDATE, RESIGNDATE, SAL, COMM, DEPTNO)
    VALUES(14, '박내일', 'REPORTER', 3, '010-0101-1010', 'parktomorrow@gmail.com', '경기도 양주시 고암길 306-40, 200동 501호', '18/02/02', NULL, 1500000, 250000, 2);
    
SELECT *
FROM CAEMP;

INSERT INTO CAEMP
    VALUES(15, '김성경', 'EDITOR', 8, '010-1010-0101', 'kimbible@gmail.com', '서울특별시 은평구 불광로 111-01 101호', '18/02/02', NULL, 1500000, 250000, 1);

SELECT *
FROM CAEMP;

UPDATE CAEMP
SET EMPNO = 99;

SELECT *
FROM CAEMP;

UPDATE CAEMP
SET JOB = 'REPORTER';

DELETE FROM CAEMP;

SELECT *
FROM CAEMP;

ROLLBACK;

SELECT *
FROM CAEMP;

SELECT EMPNO, NAME, JOB, SAL, COMM
FROM CAEMP;

SELECT ALL JOB
FROM CAEMP;

SELECT JOB
FROM CAEMP;

SELECT DISTINCT JOB
FROM CAEMP;

SELECT *
FROM CAEMP;

SELECT NAME AS 직원명, JOB AS 직책, HIREDATE AS 입사일, SAL AS 급여, COMM AS 상여
FROM CAEMP;

SELECT NAME 직원명, JOB 직책, HIREDATE 입사일, SAL 급여, COMM 상여
FROM CAEMP;

SELECT NAME "직원 이름", JOB "담당 업무", HIREDATE "입사 일자", SAL "급여", COMM "상여"
FROM CAEMP;

SELECT NAME 직원명, SAL + COMM "실수령액"
FROM CAEMP;

SELECT NAME 직원명, (SAL + COMM)*12 연봉
FROM CAEMP;