/*Exercise3_WHERE 조건절
Update : 2018-02-18, Kang Han.

아래의 SQL은 『SQL 전문가 가이드』에 따른 연습입니다.*/

/*p.210 예제*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = K02;
/*위 SQL은 실행 결과 오류를 발생시킨다.*/

/*수정 후 다시 실행한다.*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02';

DESCRIBE PLAYER;

/*아래 SQL은 TEAM_ID가 'K02'인 행이 제대로 추출되는지 확인하고자 내가 작성한 SQL이다.*/
SELECT PLAYER_NAME 선수이름, TEAM_ID 팀, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02';

/*3번째 요구 사항 : 포지션이 미드필더(MF)*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE POSITION = 'MF';

/*4번째 요구 사항 : '키가 170센티미터 이상'*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE HEIGHT >= 170;


/*p.213~ SQL 연산자*/
/*IN (list) 연산자*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID IN ('K02','K07');

DESCRIBE PLAYER;

/*다음 SQL 문장은 실행 결과 내가 원하는 TEAM_ID를 가진 행이 제대로 출력되는지
확인하기 위해 내가 고쳐서 실행한 것이다.*/
SELECT PLAYER_NAME 선수이름, TEAM_ID 팀, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID IN ('K02','K07');

/*예제*/
SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE (JOB, DEPTNO) IN (('MANAGER',20),('CLERK',30));

/*예제*/
SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE JOB IN ('MANAGER','CLERK')
AND DEPTNO IN (20,30);


/*LIKE 연산자*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE POSITION LIKE 'MF';

/*wildcard 사용*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE PLAYER_NAME LIKE '장%';


/*BETWEEN a AND b 연산자*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE HEIGHT BETWEEN 170 AND 180;


/*IS NULL 연산자*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE POSITION = NULL;
/*위 SQL 문장 실행 결과, 문법 에러가 나지는 않았지만
WHERE 절의 조건이 FALSE가 되어, 결과적으로 의미 없는 SQL이 됐다.*/

SELECT PLAYER_NAME 선수이름, POSITION 포지션, TEAM_ID
FROM PLAYER
WHERE POSITION IS NULL;


/*논리 연산자*/
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
AND HEIGHT >= 170;

DESCRIBE PLAYER;
/*다음 SQL 문장은 원하는 TEAM_ID의 행들이 제대로 출력되는지 확인하기 위해
내가 위의 SQL 문장을 수정한 것이다.*/
SELECT PLAYER_NAME 선수이름, TEAM_ID 팀, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
AND HEIGHT >= 170;

SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID IN ('K02','K07')
AND POSITION = 'MF';

/*다음 SQL 문장은 원하는 TEAM_ID의 행들이 제대로 출력되는지 확인하기 위해
내가 위의 SQL 문장을 수정한 것이다.*/
SELECT PLAYER_NAME 선수이름, TEAM_ID 팀, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID IN ('K02','K07')
AND POSITION = 'MF';


/*pp.220~221 예제*/
SELECT PLAYER_NAME 선수이름, TEAM_ID 팀, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02' OR TEAM_ID = 'K07'
AND POSITION = 'MF'
AND HEIGHT >= 170
AND HEIGHT <= 180;

/*괄호 사용한 수정.*/
SELECT PLAYER_NAME 선수이름, TEAM_ID 팀, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE (TEAM_ID = 'K02' OR TEAM_ID = 'K07')
AND POSITION = 'MF'
AND HEIGHT >= 170
AND HEIGHT <= 180;

/*같은 출력 결과를 내놓지만 IN (list)와 BETWEEN a AND b 연산자를 활용*/
SELECT PLAYER_NAME 선수이름, TEAM_ID 팀, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID IN ('K02','K07')
AND POSITION = 'MF'
AND HEIGHT BETWEEN 170 AND 180;


/*부정 연산자*/
SELECT PLAYER_NAME 선수이름, TEAM_ID 팀, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
AND NOT POSITION = 'MF'
AND NOT HEIGHT BETWEEN 175 AND 185;

/*Oracle. 위의 SQL과 아래 SQL은 같은 내용을 나타내는 SQL이다.*/
SELECT PLAYER_NAME 선수이름, TEAM_ID 팀, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
AND POSITION <> 'MF'
AND HEIGHT NOT BETWEEN 175 AND 185;

/*국적 칼럼이 NULL이 아닌 선수와 국적.*/
SELECT PLAYER_NAME 선수이름, NATION 국적
FROM PLAYER
WHERE NATION IS NOT NULL;


/*ROWNUM*/
SELECT PLAYER_NAME
FROM PLAYER
WHERE ROWNUM = 1;

SELECT PLAYER_NAME
FROM PLAYER
WHERE ROWNUM <= 1;

SELECT PLAYER_NAME
FROM PLAYER
WHERE ROWNUM < 2;

/*ROWNUM _ 예컨대 3행을 출력하려고 한다면 다음과 같이 SQL 문장을 써야 한다.*/
SELECT PLAYER_NAME
FROM PLAYER
WHERE ROWNUM <= 3;

SELECT PLAYER_NAME
FROM PLAYER
WHERE ROWNUM < 4;

/*고유한 키 또는 인덱스를 만드는 예제 실행.*/
/*PLAYER 테이블을 임시로 복사하기.*/
/*이는 CTAS(Create Table ~ As Select ~) 방법(SQLD 교재 pp.167~168)을 이용한 것이다.*/
CREATE TABLE PLAYER_TEMP
AS SELECT * FROM PLAYER;

/*ROWNUM이 입력될 COLUMN 추가.*/
ALTER TABLE PLAYER_TEMP
ADD (TEST NUMBER(3));

DESCRIBE PLAYER_TEMP;

UPDATE PLAYER_TEMP
SET TEST = ROWNUM;

SELECT PLAYER_NAME 선수명, TEST
FROM PLAYER_TEMP;

/*연습을 위해 만든 'PLAYER_TEMP' table 삭제.*/
DROP TABLE PLAYER_TEMP;